# q11_dynamic_libray_1

CC = g++
CFLAGS = 
OBJS = lib1/libfantastic.so

all: q11_dynamic_libray_1
q11_dynamic_libray_1: main.cpp $(OBJS)
	$(CC) $(CFLAGS) main.cpp $(OBJS) -o q11_dynamic_libray1
clean:
	rm -rf q11_dynamic_libray_1 *.o
